<%@ Page Title="" Language="VB" MasterPageFile="~/Master.master" AutoEventWireup="false" CodeFile="StudentHomePage.aspx.vb" Inherits="StudentHomePage" %>

<%@ MasterType VirtualPath="~/Master.master" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">


    <style type="text/css">
        .MyTabStyle .ajax__tab_header {
            font-family: "Helvetica Neue", Arial, Sans-Serif;
            font-size: 12pt;
            font-weight: bold;
            display: block;
        }

            .MyTabStyle .ajax__tab_header .ajax__tab_outer {
                padding-left: 3px;
                margin-right: 3px;
                background-size: auto;
                border-spacing: 3px;
                background-image: url(../../Images/OldPaperNoEdge.gif);
                border-width: 15px;
                border-image: url(../../Images/OldPaper.gif) 85 58 stretch;
            }

            .MyTabStyle .ajax__tab_header .ajax__tab_inner {
                padding: 3px 10px 2px 0px;
            }

        .MyTabStyle .ajax__tab_hover .ajax__tab_outer {
            background-color: #ff0000;
        }

        .MyTabStyle .ajax__tab_hover .ajax__tab_inner {
            color: #fff;
        }

        .MyTabStyle .ajax__tab_hover .ajax__tab_tab {
            color: #ffffff;
        }

        .MyTabStyle .ajax__tab_active .ajax__tab_outer {
            border-bottom-color: #ffffff;
            background-color: #04467f;
        }

        .MyTabStyle .ajax__tab_active .ajax__tab_inner {
            color: #04467f;
            border-color: #333;
        }

        .MyTabStyle .ajax__tab_active .ajax__tab_tab {
            color: #ffffff;
        }

        .MyTabStyle .ajax__tab_header .ajax__tab_outer {
            border-bottom-color: #ffffff;
            background-color: #04467f;
        }

        .MyTabStyle .ajax__tab_header .ajax__tab_inner {
            color: #fff;
            border-color: #333;
        }

        .MyTabStyle .ajax__tab_header .ajax__tab_tab {
            color: #ffffff;
        }

        .MyTabStyle .ajax__tab_body {
            font-family: verdana,tahoma,helvetica;
            font-size: 10pt;
            padding-left: 0;
            padding-right: 0;
            padding-top: 0;
            padding-bottom: 20pt;
            background-size: auto;
            border-spacing: 3px;
            background-image: url(../../Images/OldPaperNoEdge.gif);
            border-width: 20px;
            border-image: url(../../Images/OldPaper.gif) 85 58 stretch;
        }
    </style>

    <ajaxToolkit:ToolkitScriptManager runat="server" />
    <ajaxToolkit:TabContainer ID="container" runat="server" CssClass="MyTabStyle" UseVerticalStripPlacement="false">
        <ajaxToolkit:TabPanel ID="tabStudents" runat="server"
            CssClass="MyTabStyle"
            HeaderText="Take Test">
            <ContentTemplate>
                <asp:Table runat="server" HorizontalAlign="Center">
                    <asp:TableRow>
                        <asp:TableCell>
                            <asp:Table runat="server" Width="100%" SkinID="White">
                                <asp:TableRow HorizontalAlign="Center">
                                    <asp:TableCell>
                                        <asp:Label ID="lblSelectTestPage" runat="server" Text="Select Test" Font-Size="30pt" SkinID="White" />
                                    </asp:TableCell>
                                </asp:TableRow>
                                <asp:TableRow HorizontalAlign="Center">
                                    <asp:TableCell>
                                        <asp:GridView ID="grvTest" runat="server"
                                            AllowPaging="True"
                                            AllowSorting="True"
                                            AutoGenerateColumns="False"
                                            AutoGenerateDeleteButton="False"
                                            AutoGenerateEditButton="False"
                                            DataKeyNames="TestID"
                                            DataSourceID="sdsTest"
                                            PageSize="10"
                                            SkinID="gridViewSkin"
                                            ShowFooter="False">
                                            <Columns>
                                                <asp:TemplateField HeaderText="TestID" SortExpression="TestID" Visible="false">
                                                    <ItemTemplate>
                                                        <asp:Label ID="lblTestID" runat="server" Text='<%# Bind("TestID")%>'></asp:Label>
                                                    </ItemTemplate>
                                                </asp:TemplateField>
                                                <asp:TemplateField HeaderText="Class" SortExpression="Class">
                                                    <ItemTemplate>
                                                        <asp:Label ID="lblClass" runat="server" Text='<%# Bind("Class")%>'></asp:Label>
                                                    </ItemTemplate>
                                                </asp:TemplateField>
                                                <asp:TemplateField HeaderText="Test" SortExpression="Test">
                                                    <ItemTemplate>
                                                        <asp:Label ID="lblTest" runat="server" Text='<%# Bind("Test")%>'></asp:Label>
                                                    </ItemTemplate>
                                                </asp:TemplateField>
                                                <asp:TemplateField HeaderText="Description" SortExpression="Description">
                                                    <ItemTemplate>
                                                        <asp:Label ID="Description" runat="server" Text='<%# Bind("Description")%>'></asp:Label>
                                                    </ItemTemplate>
                                                </asp:TemplateField>
                                                <asp:TemplateField HeaderText="Region" SortExpression="Region">
                                                    <ItemTemplate>
                                                        <asp:Label ID="Region" runat="server" Text='<%# Bind("Region")%>'></asp:Label>
                                                    </ItemTemplate>
                                                </asp:TemplateField>
                                                <asp:TemplateField HeaderText="Type" SortExpression="Type">
                                                    <ItemTemplate>
                                                        <asp:Label ID="Type" runat="server" Text='<%# Bind("Type")%>'></asp:Label>
                                                    </ItemTemplate>
                                                </asp:TemplateField>
                                                <asp:TemplateField ShowHeader="False">
                                                    <ItemTemplate>
                                                        <asp:Button ID="btnTakeTest" runat="server" CausesValidation="True"
                                                            CommandName="TakeTest" CommandArgument="<%# CType(Container,GridViewRow).RowIndex %>" Text="Take Test" Width="60pt" />
                                                    </ItemTemplate>
                                                </asp:TemplateField>
                                            </Columns>
                                        </asp:GridView>
                                        <asp:SqlDataSource ID="sdsTest" runat="server"
                                            ConnectionString="<%$ ConnectionStrings:MapQuizConnectionString %>"></asp:SqlDataSource>
                                    </asp:TableCell>
                                </asp:TableRow>
                            </asp:Table>
                        </asp:TableCell>
                    </asp:TableRow>
                </asp:Table>

            </ContentTemplate>
        </ajaxToolkit:TabPanel>
        <ajaxToolkit:TabPanel ID="tabStudentTestResultsReport" runat="server"
            CssClass="MyTabStyle"
            HeaderText="Test Results Report">
            <ContentTemplate>
                <asp:Table runat="server" HorizontalAlign="Center">
                    <asp:TableRow>
                        <asp:TableCell>
                            <asp:Table runat="server" Width="100%" SkinID="White">
                                <asp:TableRow HorizontalAlign="Center">
                                    <asp:TableCell>
                                        <asp:Label runat="server" Text="Test Results Report" Font-Size="30pt" SkinID="White" />
                                    </asp:TableCell>
                                </asp:TableRow>
                                <asp:TableRow HorizontalAlign="Center">
                                    <asp:TableCell HorizontalAlign="Center">
                                        <asp:Table runat="server">
                                            <asp:TableRow>
                                                <asp:TableCell>
                                                    <asp:Table runat="server">
                                                        <asp:TableRow>
                                                            <asp:TableCell>
                                                                <asp:Label runat="server" Text="Student:" Font-Size="15pt" SkinID="White"/>
                                                            </asp:TableCell>
                                                            <asp:TableCell>
                                                                <asp:Label ID="lblStudentFullName" runat="server" Font-Size="15pt" SkinID="White" />
                                                            </asp:TableCell>
                                                        </asp:TableRow>
                                                        <asp:TableRow>
                                                            <asp:TableCell>
                                                                <asp:Label runat="server" Text="Grade:" Font-Size="15pt" SkinID="White"/>
                                                            </asp:TableCell>
                                                            <asp:TableCell>
                                                                <asp:Label ID="lblGrade" runat="server" Text="Test Not Selected" Font-Size="15pt" SkinID="White" />
                                                            </asp:TableCell>
                                                        </asp:TableRow>
                                                    </asp:Table>
                                                </asp:TableCell>
                                                <asp:TableCell>
                                                    <asp:Table runat="server">
                                                        <asp:TableRow>
                                                            <asp:TableCell>
                                                                <asp:Label runat="server" Text="Test:" Font-Size="15pt" SkinID="White"/>
                                                            </asp:TableCell>
                                                            <asp:TableCell>
                                                                <asp:DropDownList ID="ddlTestSelection" runat="server" Font-Size="11pt" AutoPostBack="true" EnableViewState="true" />
                                                            </asp:TableCell>
                                                        </asp:TableRow>
                                                        <asp:TableRow>
                                                            <asp:TableCell>
                                                                <asp:Label runat="server" Text="Score:" Font-Size="15pt" SkinID="White"/>
                                                            </asp:TableCell>
                                                            <asp:TableCell>
                                                                <asp:Label ID="lblScore" runat="server" Text="70 out of 75" Font-Size="15pt" SkinID="White" />
                                                            </asp:TableCell>
                                                        </asp:TableRow>
                                                    </asp:Table>
                                                </asp:TableCell>
                                            </asp:TableRow>
                                        </asp:Table>
                                    </asp:TableCell>
                                </asp:TableRow>
                                <asp:TableRow HorizontalAlign="Center">
                                    <asp:TableCell>
                                        <asp:GridView ID="grvStudentTestResultsReport" runat="server"
                                            AllowPaging="True"
                                            AllowSorting="True"
                                            AutoGenerateColumns="False"
                                            AutoGenerateDeleteButton="False"
                                            AutoGenerateEditButton="False"
                                            DataKeyNames="StudentTestID"
                                            DataSourceID="sdsStudentTestResultsReport"
                                            PageSize="80"
                                            SkinID="gridViewSkin"
                                            ShowFooter="False">
                                            <Columns>
                                                <asp:TemplateField HeaderText="Region" SortExpression="Region">
                                                    <ItemTemplate>
                                                        <asp:Label ID="lblRegion" runat="server" Text='<%# Bind("Region")%>'></asp:Label>
                                                    </ItemTemplate>
                                                </asp:TemplateField>
                                                <asp:TemplateField HeaderText="State" SortExpression="State">
                                                    <ItemTemplate>
                                                        <asp:Label ID="lblState" runat="server" Text='<%# Bind("State")%>'></asp:Label>
                                                    </ItemTemplate>
                                                </asp:TemplateField>
                                                <asp:TemplateField HeaderText="Student Answer" SortExpression="StudentAnswer">
                                                    <ItemTemplate>
                                                        <asp:Label ID="lblAnswer" runat="server" Text='<%# Bind("StudentAnswer")%>'></asp:Label>
                                                    </ItemTemplate>
                                                </asp:TemplateField>
                                                <asp:TemplateField HeaderText="Correct Answer" SortExpression="CorrectAnswer">
                                                    <ItemTemplate>
                                                        <asp:Label ID="lblCorrectAnswer" runat="server" Text='<%# Bind("CorrectAnswer")%>'></asp:Label>
                                                    </ItemTemplate>
                                                </asp:TemplateField>
                                                <asp:TemplateField HeaderText="Accuracy" SortExpression="Accuracy">
                                                    <ItemTemplate>
                                                        <asp:Label ID="lblAccuracy" runat="server" Text='<%# Bind("Accuracy")%>'></asp:Label>
                                                    </ItemTemplate>
                                                </asp:TemplateField>
                                            </Columns>
                                        </asp:GridView>
                                        <asp:SqlDataSource ID="sdsStudentTestResultsReport" runat="server"
                                            ConnectionString="<%$ ConnectionStrings:MapQuizConnectionString %>"></asp:SqlDataSource>
                                        <asp:SqlDataSource ID="sdsTestName" runat="server"
                                            ConnectionString="<%$ ConnectionStrings:MapQuizConnectionString %>"></asp:SqlDataSource>
                                    </asp:TableCell>
                                </asp:TableRow>
                            </asp:Table>
                        </asp:TableCell>
                    </asp:TableRow>
                </asp:Table>
            </ContentTemplate>
        </ajaxToolkit:TabPanel>
        <ajaxToolkit:TabPanel ID="tabStudentMultiTestResultsReport" runat="server"
            CssClass="MyTabStyle"
            HeaderText="Test History Report">
            <ContentTemplate>
                <asp:Table runat="server" HorizontalAlign="Center">
                    <asp:TableRow>
                        <asp:TableCell>
                            <asp:Table runat="server" Width="100%" SkinID="White">
                                <asp:TableRow HorizontalAlign="Center">
                                    <asp:TableCell>
                <asp:Label runat="server" Text="Test History Report" Font-Size="30pt" SkinID="White" />
                                    </asp:TableCell>
                                </asp:TableRow>
                                <asp:TableRow HorizontalAlign="Center">
                                    <asp:TableCell HorizontalAlign="Center">
                                        <asp:Table runat="server">
                                            <asp:TableRow>
                                                <asp:TableCell>
                                                    <%--NOT NEEDED NOW--%>
                                                </asp:TableCell>
                                            </asp:TableRow>
                                        </asp:Table>
                                    </asp:TableCell>
                                </asp:TableRow>
                                <asp:TableRow HorizontalAlign="Center">
                                    <asp:TableCell>
                                        <asp:GridView ID="grvStudentMultiTestResultsReport" runat="server"
                                            AllowPaging="True"
                                            AllowSorting="True"
                                            AutoGenerateColumns="False"
                                            AutoGenerateDeleteButton="False"
                                            AutoGenerateEditButton="False"
                                            DataKeyNames="StudentID"
                                            DataSourceID="sdsStudentMultiTestResultsReport"
                                            PageSize="25"
                                            SkinID="gridViewSkin"
                                            ShowFooter="False">
                                            <Columns>
                                                <asp:TemplateField HeaderText="Test" SortExpression="Test">
                                                    <ItemTemplate>
                                                        <asp:Label ID="lblTest" runat="server" Text='<%# Bind("Test")%>'></asp:Label>
                                                    </ItemTemplate>
                                                </asp:TemplateField>
                                                <asp:TemplateField HeaderText="Start Time" SortExpression="StartTime">
                                                    <ItemTemplate>
                                                        <asp:Label ID="lblStartTime" runat="server" Text='<%# Bind("StartTime")%>'></asp:Label>
                                                    </ItemTemplate>
                                                </asp:TemplateField>
                                                <asp:TemplateField HeaderText="Finish Time" SortExpression="FinishTime">
                                                    <ItemTemplate>
                                                        <asp:Label ID="lblFinishTime" runat="server" Text='<%# Bind("FinishTime")%>'></asp:Label>
                                                    </ItemTemplate>
                                                </asp:TemplateField>
                                                <asp:TemplateField HeaderText="Score" SortExpression="Score">
                                                    <ItemTemplate>
                                                        <asp:Label ID="lblScoreByClass" runat="server" Text='<%# Bind("Score")%>'></asp:Label>
                                                    </ItemTemplate>
                                                </asp:TemplateField>
                                                <asp:TemplateField HeaderText="Grade" SortExpression="Grade">
                                                    <ItemTemplate>
                                                        <asp:Label ID="lblGrade" runat="server" Text='<%# Bind("Grade")%>'></asp:Label>
                                                    </ItemTemplate>
                                                </asp:TemplateField>
                                            </Columns>
                                        </asp:GridView>
                                        <asp:SqlDataSource ID="sdsStudentMultiTestResultsReport" runat="server"
                                            ConnectionString="<%$ ConnectionStrings:MapQuizConnectionString %>"></asp:SqlDataSource>
                                    </asp:TableCell>
                                </asp:TableRow>
                            </asp:Table>
                        </asp:TableCell>
                    </asp:TableRow>
                </asp:Table>
            </ContentTemplate>
        </ajaxToolkit:TabPanel>
        <ajaxToolkit:TabPanel ID="tabChangeStudentPassword" runat="server"
            CssClass="MyTabStyle"
            HeaderText="Change Password">
            <ContentTemplate>
                <asp:Table runat="server" HorizontalAlign="Center">
                    <asp:TableRow>
                        <asp:TableCell>
                            <asp:Table runat="server" HorizontalAlign="Center" Width="100%" SkinID="White">
                                <asp:TableRow HorizontalAlign="Center">
                                    <asp:TableCell HorizontalAlign="Center">
                                        <asp:Label runat="server" Text="Change Password" Font-Size="30pt" SkinID="White" />
                                    </asp:TableCell>
                                </asp:TableRow>
                                <asp:TableRow HorizontalAlign="Center">
                                    <asp:TableCell>
                                        <asp:Label ID="lblChangePasswordErrorMessage" runat="server" Visible="false" Font-Size="14pt" />
                                    </asp:TableCell>
                                </asp:TableRow>
                            </asp:Table>
                            <asp:Table runat="server" HorizontalAlign="Center" Width="100%" SkinID="White">
                                <asp:TableRow HorizontalAlign="Left">
                                    <asp:TableCell HorizontalAlign="Right">
                                        <asp:Label ID="lblCurrentPasswordText" runat="server" Text="Current Password: " Font-Size="Large"/>
                                    </asp:TableCell>
                                    <asp:TableCell HorizontalAlign="Left">
                                        <asp:Label ID="lblCurrentPassword" runat="server" Font-Size="Large"/>
                                    </asp:TableCell>
                                </asp:TableRow>
                                <asp:TableRow HorizontalAlign="Right">
                                    <asp:TableCell HorizontalAlign="Right">
                                        <asp:Label ID="lblNewPassword" runat="server" Text="New Password: " Font-Size="Large" />
                                    </asp:TableCell>
                                    <asp:TableCell HorizontalAlign="Left">
                                        <asp:TextBox ID="txtNewPassword" runat="server" Font-Size="Large" />
                                    </asp:TableCell>
                                </asp:TableRow>
                            </asp:Table>
                        </asp:TableCell>
                    </asp:TableRow>
                    <asp:TableRow HorizontalAlign="Center">
                        <asp:TableCell HorizontalAlign="Center">
                            <asp:Button ID="btnChangePassword" runat="server" Text="Change Password" Font-Size="Large" />
                        </asp:TableCell>
                    </asp:TableRow>
                </asp:Table>
            </ContentTemplate>
        </ajaxToolkit:TabPanel>
    </ajaxToolkit:TabContainer>
</asp:Content>

